image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - cd Frontend/

stages:
  - develop
  - production

develop:
  type: deploy
  stage: develop
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_DEVELOP --api-key=$HEROKU_API_KEY
  only:
    - develop

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
